name: v2.0.0

on:
  push:
    branches: [ v2.0.0 ]
  pull_request:
    branches: [ v2.0.0 ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        dotnet-version: [ '6.0.x' ]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup v2.0.0
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
